### ISSUE TITLE
New Wardround Micro elcid@UCH Release

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-ideas#32]
Process: 
- [x] Create new release branches for elCID, OPAL, OPAT, Walkin
- [x] Backport the Wardround related 0.6.x updates to each of the above
- [x] Create a new Heroku instance (0.5.3)
- [x] Add a significant amount of random data to the instance, ensure many episodes are on DLW
- [ ] Acceptance testing
- [ ] Deploy to ELCIDT (With live data snapshot)
- [ ] Test speed with real data
- [ ] Deploy to ELCIDL

**Comment by michaeledwardmarks** [comment]
- [ ] Confirm Final Diagnosis button doesnt work on DLW or Consultant Review WR

**Comment by michaeledwardmarks** [comment]
Updates
- adding to ward rounds now seems to work again
- Behaviour of OPAT-Review and OPAT-Current appears correct

**Comment by michaeledwardmarks** [comment]
- Loading time <5 seconds on heroku for ward round with 80 people
- Moving between people once WR loaded <3 seconds

I've been through Stories once already and other things seem correct
@GabPoll will also go through all stories and I'll do them one more time at least today.
If we deploy to elCID-T today then I can look this PM otherwise will do tomorrow

**Comment by davidmiller** [comment]
I think this is now long since dead
